---

- hosts: ubuntu
  become: true
  tasks:

  - name: install chronyd and vim
    apt: 
      name:
        - chrony
        - vim-nox
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install chronyd and vim
    dnf:
      name:
        - chrony
        - vim-nox
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
