---

- hosts: ubuntu
  become: true
  tasks:

  - name: update repos
    apt:
      update_cache: yes

  - name: install chronyd
    apt: 
      name: chrony

  - name: install vim
    apt:
      name: vim-nox

